const SUPABASE_URL='https://fxluchtdfpediivhoksl.supabase.co';const SUPABASE_KEY='sb_publishable_y2OadDy1zy8QlWy-YAcdlg_uzAYMLzj';const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const CLIENT_CLAIM_URL='https://fxluchtdfpediivhoksl.supabase.co/functions/v1/sculptify-client-claim';const $=s=>document.querySelector(s);let current=null;
function parse3(v){return v.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [name,description,price]=x.split('|').map(y=>y.trim());return{name,description,price}})}
function parse2(v){return v.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [question,answer]=x.split('|').map(y=>y.trim());return{question,answer}})}
function lines3(a){return (Array.isArray(a)?a:[]).map(x=>[x.name||'',x.description||'',x.price||''].join(' | ')).join('\n')}
function lines2(a){return (Array.isArray(a)?a:[]).map(x=>[x.question||'',x.answer||''].join(' | ')).join('\n')}
async function refresh(){
 const {data:{user}}=await db.auth.getUser();if(!user){$('#login').classList.remove('hidden');$('#workspace').classList.add('hidden');return;}
 const session=(await db.auth.getSession()).data.session;if(session){await fetch(CLIENT_CLAIM_URL,{method:'POST',headers:{'Authorization':'Bearer '+session.access_token}}).catch(()=>{});}
 $('#login').classList.add('hidden');$('#workspace').classList.remove('hidden');
 const {data:members}=await db.from('sculptify_client_members').select('site_id,role').eq('user_id',user.id);
 const ids=(members||[]).map(x=>x.site_id);if(!ids.length){$('#sites').innerHTML='<p class="small">No business template is assigned to this email yet.</p>';return;}
 const {data:sites}=await db.from('sculptify_client_sites').select('*').in('id',ids).order('created_at');
 $('#sites').innerHTML=(sites||[]).map(s=>'<div class="site-row"><b>'+s.business_name+'</b><small>'+s.vertical+' • '+s.status+'</small><button class="btn outline edit-site" data-id="'+s.id+'">Edit</button></div>').join('');
 document.querySelectorAll('.edit-site').forEach(b=>b.onclick=()=>openSite((sites||[]).find(s=>s.id===b.dataset.id)));
 if(sites?.length===1)openSite(sites[0]);
}
function openSite(s){current=s;$('#editor').classList.remove('hidden');$('#business-name').value=s.business_name||'';$('#vertical').value=s.vertical||'';$('#location').value=s.location||'';$('#contact-email').value=s.contact_email||'';$('#contact-phone').value=s.contact_phone||'';$('#logo-url').value=s.logo_url||'';$('#hero-title').value=s.hero_title||'';$('#hero-subtitle').value=s.hero_subtitle||'';$('#primary').value=s.primary_color||'#d896ff';$('#secondary').value=s.secondary_color||'#e9c77f';$('#accent').value=s.accent_color||'#ff91b8';$('#background').value=s.background_color||'#09070a';$('#booking-url').value=s.booking_url||'';$('#store-url').value=s.store_url||'';$('#cta-label').value=s.cta_label||'Book Now';$('#slug').value=s.slug||'';$('#services').value=lines3(s.services);$('#faqs').value=lines2(s.faq);$('#products').value=lines3(s.products);}
function payload(){return{business_name:$('#business-name').value.trim(),vertical:$('#vertical').value.trim(),location:$('#location').value.trim()||null,contact_email:$('#contact-email').value.trim()||null,contact_phone:$('#contact-phone').value.trim()||null,logo_url:$('#logo-url').value.trim()||null,hero_title:$('#hero-title').value.trim(),hero_subtitle:$('#hero-subtitle').value.trim(),primary_color:$('#primary').value,secondary_color:$('#secondary').value,accent_color:$('#accent').value,background_color:$('#background').value,booking_url:$('#booking-url').value.trim()||null,store_url:$('#store-url').value.trim()||null,cta_label:$('#cta-label').value.trim()||'Book Now',services:parse3($('#services').value),faq:parse2($('#faqs').value),products:parse3($('#products').value),updated_at:new Date().toISOString()}}
$('#login-btn').onclick=async()=>{const email=$('#email').value.trim();if(!email){$('#login-status').textContent='Enter your email.';return;}$('#login-status').textContent='Sending secure sign-in link…';const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname,shouldCreateUser:true}});$('#login-status').textContent=error?error.message:'Check your email for the sign-in link.';};
$('#editor').onsubmit=async e=>{e.preventDefault();if(!current)return;$('#save-status').textContent='Saving…';const {data,error}=await db.from('sculptify_client_sites').update({...payload(),status:'draft'}).eq('id',current.id).select('*').single();if(error){$('#save-status').textContent='Could not save: '+error.message;return;}current=data;$('#save-status').textContent='Draft saved.';await refresh();};
$('#publish').onclick=async()=>{if(!current)return;$('#save-status').textContent='Publishing…';const {data,error}=await db.from('sculptify_client_sites').update({...payload(),status:'published',published_at:new Date().toISOString()}).eq('id',current.id).select('*').single();if(error){$('#save-status').textContent='Could not publish: '+error.message;return;}current=data;$('#save-status').textContent='Published. Your live page is ready.';window.open('./client.html?site='+encodeURIComponent(current.slug),'_blank');await refresh();};
$('#preview').onclick=()=>{if(current)window.open('./client.html?site='+encodeURIComponent(current.slug)+'&preview=1','_blank')};
db.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();